#!/usr/bin/env bash
# Install nginx on your server
# Nginx should be listening on port 80

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
  sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Strating nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up redirect_me to a youtube
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. \n"
