#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, say bad if 4 and good luck if 8

i=0
while [ $i -lt 10 ]
do
i=$((i + 1))
if [ $i -eq 4 ]
then
  echo "bad luck"
elif [ $i -eq 8 ]
then
  echo "good luck"
else
  echo "Best School"
fi
done
