#!/usr/bin/env bash
# This script display number from 1 - 20 and say bad luck from China on 4, bad luck from Japan on 9 and bad luck from Italy on 17

i=1
while [ $i -le 20 ]
do
  echo $i
  case $i in
  4)
    echo "bad luck from China"
  ;;
  9)
    echo "bad luck from Japan"
  ;;
  17)
    echo "bad luck from Italy"
  ;;
  esac
  i=$((i+1))
done
